[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "euchre"
version = "1.2.1"
dependencies = [
    "typeguard",
    "colorama"
]

[tool.setuptools.packages]
find = {where = ["src"]}